### ISSUE TITLE
Getting P2PKH address when requested fresh address from ZPUB  

### ISSUE THREAD

**Issue by elkimek** [InvertedX/sentinelx#1]
Hi,

I'm testing lastest apk. I imported a ZPUB (bech32) but when I hit the small QR circle button at the bottom left to get fresh receive address, I'll get P2PKH address.

**Comment by InvertedX** [comment]
did you add any legacy addresses ?

**Comment by elkimek** [comment]
Nope. Just fresh install for first time and added Whirlpool ZPUB. Nothing else.

**Comment by InvertedX** [comment]
i think i found the issue, you're registered ZPUB as non-segwit xpub (See the tabs in the Track screen) 
you need to register zpubs as segwit wallet (See the tabs in the Track screen)

the issue is noted, and will address in next release 

thank you for reporting

**Comment by elkimek** [comment]
Yep, correct :) Made a new track as BIP 84 the old one was BIP44.
