### ISSUE TITLE
FAB makes it difficult to erase wallet

### ISSUE THREAD

**Issue by pajasevi** [InvertedX/sentinelx#2]
Because the FAB is floating above card action buttons, it is very difficult to erase or edit "watch wallet".
Please add some padding so the user can scroll more and reveal those action buttons.
![Screenshot_20200313-134035~2](https://user-images.githubusercontent.com/2407408/76653883-f71bff00-6569-11ea-909a-1cf3a7fa1248.png)

**Comment by InvertedX** [comment]
fixed in [67af394](https://github.com/InvertedX/sentinelx/commit/67af3948215cb261b515a6205fddeb549fd8e497)
