### ISSUE TITLE
Tor process is left hanging after closing the app

### ISSUE THREAD

**Issue by pajasevi** [InvertedX/sentinelx#3]
After closing the app properly with backbutton, the Tor process is left in the background, leaving the notification as disconnected.

![Screenshot_20200313-203648](https://user-images.githubusercontent.com/2407408/76654217-c7b9c200-656a-11ea-9722-7607b1641596.png)

**Comment by InvertedX** [comment]
fixed in b611ebd6a7045f48b69bc89c91f4b3ec34956d88
