### ISSUE TITLE
Dojo connection not reliable

### ISSUE THREAD

**Issue by openoms** [InvertedX/sentinelx#5]
Hi,  I proceeded testing with the knowledge that SentinelX is pre-release beta software so the following needs to be viewed in the light of that.

Installed the latest v0.1.6 SentinelX APK on two Android phones with the latest updates: Oneplus 5T with the manufacturers OxygenOS and a Pixel3aXl with GrapheneOS.

Both connected to my Dojo and imported some xpubs and addresses.

When opened the app next the Tor connection was not active and SentinelX still pulled the latest transactions (likely not from my Dojo, but there is no way to tell). In the settings my Dojo Node appears, but the onion on the top right is gray.  When starting the Tor Routing it becomes green with no other difference shown.

Next I have shut down the Dojo and opened SentinelX again on both phones. Was able to add new addresses to track and the latest transactions have been pulled (clearly not from the custom backend this time).

Suggestion:
* The app should be able to signal clearly what backend it is connecting to
* Tor should be on by default
* no connections should be made to other servers if the custom backend is down.

Thank you this is a fantastic app otherwise, but there must be further privacy assurances.

EDIT:
now I am opening again and it only shows:  Connecting to dojo..
so the problem seems to be when the connection goes down in between SentinelX restarts.

The best solution might be to have a package without a hardcoded fallback. Dojo only SentinelX please!

**Comment by InvertedX** [comment]
thanks for the detailed explanation. 
i will look into it

**Comment by openoms** [comment]
Congrats on the 0.1.7 release!
Good idea exposing the  Network logs, it provides great reassurance!

BTW I did not manage to reproduce this error again so I will close this issue (and keep an eye for the logs). My wallets involved are now all migrated to new Xpubs.
